### ISSUE TITLE
python 脚本停不下来

### ISSUE THREAD

**Issue by 1998-zhang** [outlaws-bai/Galaxy#10]
![image](https://github.com/user-attachments/assets/19bd8fad-017b-4482-ad4c-da2bfe693d5a)

点击停止按钮，不能停止脚本

![image](https://github.com/user-attachments/assets/f523ce81-e386-4486-a9a1-d6d3f5a84b04)

**Comment by outlaws-bai** [comment]
汉化问题，下版本尝试解决

**Comment by outlaws-bai** [comment]
可以先别用burp汉化版，下版本会尝试兼容

**Comment by outlaws-bai** [comment]
已解决，下版本发布
