### ISSUE TITLE
插件能正常开启，但是点停止无效

### ISSUE THREAD

**Issue by HZMM98** [outlaws-bai/Galaxy#12]
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/e8230d70-a83a-4761-bdd7-2cc45cc99fa9">
点停止无效果

**Comment by outlaws-bai** [comment]
汉化burp导致的问题，可以先尝试自己打包，或等待新版3.0，今天会发

**Comment by outlaws-bai** [comment]
已发布
