### ISSUE TITLE
java17安装报错

### ISSUE THREAD

**Issue by Github3362** [outlaws-bai/Galaxy#13]
![image](https://github.com/user-attachments/assets/37537c0c-eb9e-43c2-8d38-beab5d33e899)

**Comment by outlaws-bai** [comment]
什么版本的 burp，这个还是 burp 版本过低导致的

**Comment by Github3362** [comment]
2023.4.2

**Comment by outlaws-bai** [comment]
Burp版本不低于 v2023.10.3.7 。
最好不低于这个，稍微早点的没有详细测试
