### ISSUE TITLE
Setting Tab UI未显示完全问题

### ISSUE THREAD

**Issue by Admin123456-check** [outlaws-bai/Galaxy#18]
UI显示是不是有问题，下面看着好像还有内容
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/42898e1d-7a8a-44a7-a134-f3102e3a5799">

**Comment by outlaws-bai** [comment]
确认问题，下方未显示部分为请求的静态扩展，一般不需要修改，如果需要目前可以通过  [work dir](https://github.com/outlaws-bai/Galaxy/blob/main/docs/Basic.md#work-dir)/setting.yaml下的staticExtensions 修改

**Comment by outlaws-bai** [comment]
3.2.1已修复
