### ISSUE TITLE
安装插件报错，是用新版montoya 接口编写的插件么

### ISSUE THREAD

**Issue by robot183** [outlaws-bai/Galaxy#2]
![image](https://github.com/outlaws-bai/Galaxy/assets/55733256/50d414bf-fc79-43ae-857f-d01bce691d86)

安装插件报错，是用新版montoya 接口编写的插件么？还是导出安装包的时候有问题。

**Comment by outlaws-bai** [comment]
是的，用的新版montoya，我这边的环境是
Burp运行及插件编译JAVA版本：19
Burp版本：V2023.10.3.7
Python版本：3.11
