### ISSUE TITLE
1.graal 与 java 字节数组差异；2.  graaljs stringToByteArray 无法处理中文

### ISSUE THREAD

**Issue by catzillasec** [outlaws-bai/Galaxy#20]
调用js的 stringToByteArray(str) 函数时 传入字符串‘成功’ 得到的结果为[16,159] 而在执行Java函数setcontent()时会出现报错。javascript转换的取值范围为0～255 而java为-127～128，导致溢出报错。

**Comment by outlaws-bai** [comment]
1. 可以提供函数解决
2. graaljs 没有找到办法将中文转为 utf-8 的字节数组
该问题暂时 pending

**Comment by outlaws-bai** [comment]
重新确认后，如果服务端返回的响应存在中文，不会影响插件的加解密，只有用户在代码编辑器中写了中文并调用stringToByteArray 才会出现该问题，因此关闭
