### ISSUE TITLE
在hook_request_to_server，hook_response_to_client 出现异常会导致业务流程异常

### ISSUE THREAD

**Issue by mikeccltt** [outlaws-bai/Galaxy#22]
在请求只可解密不可重新加密的情况下 client端会接收到解密后的明文 会造成无法解析的情况。在请求只可解密不可重新加密的情况下 client端会接收到解密后的明文 会造成无法解析的情况。

**Comment by outlaws-bai** [comment]
确认问题：增加保护措施，在hook_request_to_server，hook_response_to_client 异常时返回原请求/响应给客户端/服务端

**Comment by outlaws-bai** [comment]
内部评估后，决定不开发该建议，主要面临的问题是：
1.在到达 hook_request_to_server 时，这时候在 proxy 模块已经可以看到请求的 edited 是已经被 hook_request_to_burp 修改，如果要在 hook_request_to_server 做容错，没有位置可以展示hook_request_to_server执行错误了
2.不做容错的话，会影响业务流程，但细思后这反而是个好事，这样用户可以找到问题点，并慢慢将脚本调试到最好，从而顺畅的进行测试
