### ISSUE TITLE
使用 orcale jdk 启动时无法使用国密算法

### ISSUE THREAD

**Issue by heiha7789** [outlaws-bai/Galaxy#23]
使用demo网站测试，调用报错如下，新版的插件和，JDK21启动的 
![f6adfc33f8c014a243d47d66b560699](https://github.com/user-attachments/assets/83f7d232-43e7-45a9-bc0b-f772dcf9cb2c)

**Comment by outlaws-bai** [comment]
确认问题：
在 burp 自带 jre 或 orcale jdk 中找不到SM4/CBC/PKCS5Padding，后续尝试解决

**Comment by outlaws-bai** [comment]
https://github.com/outlaws-bai/Galaxy/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E7%94%A8-orcale-JDK-or-JRE-%E5%90%AF%E5%8A%A8-Burp
