### ISSUE TITLE
3.3.0 无法自动明文显示响应包

### ISSUE THREAD

**Issue by k-fire** [outlaws-bai/Galaxy#27]
burp 2024.10   openjdk 22.0.2
不出现下图选项，而且响应体仍然为密文
![image](https://github.com/user-attachments/assets/5265655b-d521-4244-af80-c5e3eaecce59)
必须要右键-解密，才能看到，3.2.1则无此问题

**Comment by outlaws-bai** [comment]
无法复现，请确认是在启动了 http hook 后，才点击的按钮触发流量。如果仍然出现该问题，可查看日志是否有报错

**Comment by k-fire** [comment]
> 无法复现，请确认是在启动了 http hook 后，才点击的按钮触发流量。如果仍然出现该问题，可查看日志是否有报错

不太清楚，有可能是我环境问题，换了台电脑好了

**Comment by outlaws-bai** [comment]
--。解决就行，祝好
