### ISSUE TITLE
http 方式增加更多加密算法示例

### ISSUE THREAD

**Issue by 123654mjx** [outlaws-bai/Galaxy#31]
![image](https://github.com/user-attachments/assets/4485edcd-5894-4e8a-b10d-d989c8c67b2a)
下方和示例中UI差的有点多，选择加密和写脚本的地方都没了

**Comment by 123654mjx** [comment]
在3.2.1中java可正常展示，http同样问题
![image](https://github.com/user-attachments/assets/6995b020-9735-4d7a-9966-db1eabb63716)

**Comment by outlaws-bai** [comment]
http  方式是需要你本地启动一个 http 服务，因此，没有写脚本的地方
<img width="801" alt="image" src="https://github.com/user-attachments/assets/840dc4c3-4fb5-4e61-a221-cdf9dd7088c9">

**Comment by 123654mjx** [comment]
https://github.com/outlaws-bai/GalaxyHttpHooker/blob/main/http_hooker_aes_cbc.py这个是案例，但是没有java那种写好的可选项了对吗

**Comment by outlaws-bai** [comment]
你是想要其他加密方式的案例吗？

**Comment by 123654mjx** [comment]
对的

**Comment by outlaws-bai** [comment]
ok，我找时间加一下

**Comment by 123654mjx** [comment]
谢谢师傅

**Comment by outlaws-bai** [comment]
别客气，有帮助可以点点 star

**Comment by outlaws-bai** [comment]
已添加
