### ISSUE TITLE
安装插件出错，怎么解决呀

### ISSUE THREAD

**Issue by Journey-design** [outlaws-bai/Galaxy#32]
![image](https://github.com/user-attachments/assets/22f2da9d-b567-4d97-9b6a-964e211790c1)

**Comment by outlaws-bai** [comment]
Burp版本不低于 v2023.10.3.7

**Comment by Journey-design** [comment]
大佬，请问哪个jar包，burpv2022.1可用呀

**Comment by outlaws-bai** [comment]
插件是使用 burp 新版的插件 api 开发的，不支持burpv2022.1

**Comment by Journey-design** [comment]
谢谢大佬，请问使用了v2023.11.1版本的bp,安装Galaxy-3.1.0-all.jar插件后，注释乱码，该怎么解决呀？修改了burp的字体没有什么效果
![image](https://github.com/user-attachments/assets/f22446e9-713a-40da-935f-1cca246b8c7d)

**Comment by outlaws-bai** [comment]
遇到问题可以先看看 faq 哈
<img width="508" alt="image" src="https://github.com/user-attachments/assets/1f68d776-5084-49b0-b74e-f81eb15be6d2">
